/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Overview',
      link: {
        type: 'doc',
        id: 'overview/index'
      },
      items: [
        'overview/about',
        'overview/pii',
        'overview/organization',
        'overview/hla',
        'overview/definitions',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {
        type: 'doc',
        id: 'concepts/index',
      },
      items: [
        'concepts/core-concepts',
        'concepts/batch-vs-streaming',
        'concepts/batch-jobs',
        'concepts/data-connectors',
        'concepts/schemas-and-contracts',
        'concepts/strm-meta',
        'concepts/masked-fields',
        'concepts/simple-schemas',
        'concepts/ccd',
      ]
    },
    {
      type: 'category',
      label: 'Quickstart',
      link: {
        type: 'doc',
        id: 'quickstart/index',
      },
      items: [
        'quickstart/creating-streams',
        'quickstart/listen-web-socket',
        'quickstart/sending-curl',
        {
          type: 'category',
          label: 'Customer Cloud Deployments',
          link: {
            type: 'doc',
            id: 'quickstart/ccd/index',
          },
          items: [
            'quickstart/ccd/self-hosted',
            'quickstart/ccd/aws-marketplace',
            'quickstart/ccd/authenticated'
          ]
        },
        'quickstart/batch-exporter',
        'quickstart/full-example',
        'quickstart/exporting-kafka',
        'quickstart/exporting-keys',
        'quickstart/grpc',
        'quickstart/simple-schema',
      ]
    },
    {
      type: 'category',
      label: 'CLI Reference',
      link: {
        type: 'doc',
        id: 'cli-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: "cli-reference"
        },
      ]
    },
    {
      type: 'doc',
      label: 'Contact',
      id: 'contact/index'
    }
  ],
};

module.exports = sidebars;
