name: Pull Request Build

on:
  push:
    branches-ignore:
      - "master"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        env:
          CI_COMMIT_REF_NAME: ${{ steps.extract_branch.outputs.branch }}
        with:
          arguments: build signMavenJavaPublication
          gradle-version: wrapper
          properties: |
            gpgPrivateKey=${{secrets.GPG_PRIVATE_KEY_BASE64_ENC}}
            gpgPassphrase=${{secrets.GPG_PASSPHRASE_BASE64_ENC}}
