name: Publish docs to gh-pages

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_branch
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        env:
          CI_COMMIT_TAG: ${{ steps.extract_branch.outputs.tag }}
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
          gradle-version: wrapper
          properties: |
            gpgPrivateKey=${{secrets.GPG_PRIVATE_KEY_BASE64_ENC}}
            gpgPassphrase=${{secrets.GPG_PASSPHRASE_BASE64_ENC}}
            sonatypeUsername=${{secrets.S01_SONATYPE_USERNAME_BASE64_ENC}}
            sonatypePassword=${{secrets.S01_SONATYPE_PASSWORD_BASE64_ENC}}
