name: Update Search Index

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed


jobs:
  publish:
    name: Update Search Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Algolia Docsearch Indexer
        uses: darrenjennings/algolia-docsearch-action@v0.2.0
        with:
          algolia_application_id: 'M24OHV52F0'
          algolia_api_key: ${{secrets.ALGOLIA_API_KEY}}
          file: './algolia-config.json'

